# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/client/'
    schedule:
      interval: 'daily'
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"

  - package-ecosystem: 'npm'
    directory: '/server/'
    schedule:
      interval: 'daily'
   automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
