# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/client/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: feat
      prefix-development: feat
    open-pull-requests-limit: 99

  - package-ecosystem: 'npm'
    directory: '/server/'
    schedule:
      interval: 'daily'
    commit-message:
      prefix: feat
      prefix-development: feat
    open-pull-requests-limit: 99
