version: "3.8"
services:
mongodb:
image: mongo
container_name: mongodb
environment:
  - PUID=1000
  - PGID=1000
volumes:
   - ./data/mongodb/mongod.conf:/etc/mongod.conf
   - ./data/mongodb/initdb.d/:/docker-entrypoint-initdb.d/
   - ./data/mongodb/database:/data/db/
ports:
  - 27017:27017
restart: unless-stopped
